server:
  port: 4132
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shopmanager
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update


